### ISSUE TITLE
can't build on OS X 10.5

### ISSUE THREAD

**Issue by jarib** [mranney/node_pcap#10]
On Leopard, I'm seeing this error

<pre>
npm info it worked if it ends with ok
npm info version 0.2.0
npm info fetch http://registry.npmjs.org/pcap/-/pcap-0.2.1.tgz
npm info install pcap@0.2.1
npm WARN bins installing to /usr/local/share/npm/bin, outside PATH
npm info install pcap@0.2.1
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.2.1 
'configure' finished successfully (0.806s)
Waf: Entering directory `/usr/local/lib/node/.npm/pcap/0.2.1/package/build'
[1/2] cxx: pcap_binding.cc -> build/default/pcap_binding_1.o
../pcap_binding.cc:5:23: error: pcap/pcap.h: No such file or directory
../pcap_binding.cc:22: error: aggregate ‘bpf_program fp’ has incomplete type and cannot be defined
../pcap_binding.cc:23: error: ‘bpf_u_int32’ does not name a type
../pcap_binding.cc:24: error: ‘bpf_u_int32’ does not name a type
../pcap_binding.cc:25: error: expected constructor, destructor, or type conversion before ‘*’ token
../pcap_binding.cc: In function ‘void PacketReady(u_char*, const pcap_pkthdr*, const u_char*)’:
../pcap_binding.cc:46: error: invalid use of undefined type ‘const struct pcap_pkthdr’
../pcap_binding.cc:40: error: forward declaration of ‘const struct pcap_pkthdr’
../pcap_binding.cc:52: error: invalid use of undefined type ‘const struct pcap_pkthdr’
../pcap_binding.cc:40: error: forward declaration of ‘const struct pcap_pkthdr’
../pcap_binding.cc:53: error: invalid use of undefined type ‘const struct pcap_pkthdr’
../pcap_binding.cc:40: error: forward declaration of ‘const struct pcap_pkthdr’
../pcap_binding.cc:54: error: invalid use of undefined type ‘const struct pcap_pkthdr’
../pcap_binding.cc:40: error: forward declaration of ‘const struct pcap_pkthdr’
../pcap_binding.cc:55: error: invalid use of undefined type ‘const struct pcap_pkthdr’
../pcap_binding.cc:40: error: forward declaration of ‘const struct pcap_pkthdr’
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> Dispatch(const v8::Arguments&)’:
../pcap_binding.cc:89: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:89: error: ‘pcap_dispatch’ was not declared in this scope
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> Open(bool, const v8::Arguments&)’:
../pcap_binding.cc:100: error: ‘PCAP_ERRBUF_SIZE’ was not declared in this scope
../pcap_binding.cc:120: error: ‘net’ was not declared in this scope
../pcap_binding.cc:120: error: ‘mask’ was not declared in this scope
../pcap_binding.cc:120: error: ‘errbuf’ was not declared in this scope
../pcap_binding.cc:120: error: ‘pcap_lookupnet’ was not declared in this scope
../pcap_binding.cc:126: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:126: error: ‘errbuf’ was not declared in this scope
../pcap_binding.cc:126: error: ‘pcap_create’ was not declared in this scope
../pcap_binding.cc:128: error: no matching function for call to ‘v8::String::New(<type error>)’
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1147: note: candidates are: static v8::Local<v8::String> v8::String::New(const char*, int)
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1150: note:                 static v8::Local<v8::String> v8::String::New(const uint16_t*, int)
../pcap_binding.cc:132: error: ‘pcap_set_snaplen’ was not declared in this scope
../pcap_binding.cc:137: error: ‘pcap_set_promisc’ was not declared in this scope
../pcap_binding.cc:142: error: ‘pcap_set_buffer_size’ was not declared in this scope
../pcap_binding.cc:147: error: ‘pcap_set_timeout’ was not declared in this scope
../pcap_binding.cc:157: error: ‘pcap_activate’ was not declared in this scope
../pcap_binding.cc:158: error: ‘pcap_geterr’ was not declared in this scope
../pcap_binding.cc:162: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:162: error: ‘errbuf’ was not declared in this scope
../pcap_binding.cc:162: error: ‘pcap_open_offline’ was not declared in this scope
../pcap_binding.cc:164: error: no matching function for call to ‘v8::String::New(<type error>)’
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1147: note: candidates are: static v8::Local<v8::String> v8::String::New(const char*, int)
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1150: note:                 static v8::Local<v8::String> v8::String::New(const uint16_t*, int)
../pcap_binding.cc:168: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:168: error: ‘errbuf’ was not declared in this scope
../pcap_binding.cc:168: error: ‘pcap_setnonblock’ was not declared in this scope
../pcap_binding.cc:169: error: no matching function for call to ‘v8::String::New(<type error>)’
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1147: note: candidates are: static v8::Local<v8::String> v8::String::New(const char*, int)
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1150: note:                 static v8::Local<v8::String> v8::String::New(const uint16_t*, int)
../pcap_binding.cc:173: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:173: error: ‘net’ was not declared in this scope
../pcap_binding.cc:173: error: ‘pcap_compile’ was not declared in this scope
../pcap_binding.cc:174: error: ‘pcap_geterr’ was not declared in this scope
../pcap_binding.cc:177: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:177: error: ‘pcap_setfilter’ was not declared in this scope
../pcap_binding.cc:178: error: ‘pcap_geterr’ was not declared in this scope
../pcap_binding.cc:186: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:186: error: ‘pcap_get_selectable_fd’ was not declared in this scope
../pcap_binding.cc:192: error: ‘pcap_datalink’ was not declared in this scope
../pcap_binding.cc:202: error: ‘DLT_IEEE802_11_RADIO’ was not declared in this scope
../pcap_binding.cc:209: error: ‘errbuf’ was not declared in this scope
../pcap_binding.cc:210: error: no matching function for call to ‘v8::String::New(<type error>)’
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1147: note: candidates are: static v8::Local<v8::String> v8::String::New(const char*, int)
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1150: note:                 static v8::Local<v8::String> v8::String::New(const uint16_t*, int)
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> FindAllDevs(const v8::Arguments&)’:
../pcap_binding.cc:232: error: ‘PCAP_ERRBUF_SIZE’ was not declared in this scope
../pcap_binding.cc:233: error: ‘pcap_if_t’ was not declared in this scope
../pcap_binding.cc:233: error: ‘alldevs’ was not declared in this scope
../pcap_binding.cc:233: error: ‘cur_dev’ was not declared in this scope
../pcap_binding.cc:235: error: ‘errbuf’ was not declared in this scope
../pcap_binding.cc:235: error: ‘pcap_findalldevs’ was not declared in this scope
../pcap_binding.cc:236: error: no matching function for call to ‘v8::String::New(<type error>)’
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1147: note: candidates are: static v8::Local<v8::String> v8::String::New(const char*, int)
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1150: note:                 static v8::Local<v8::String> v8::String::New(const uint16_t*, int)
../pcap_binding.cc:251: error: ‘pcap_addr_t’ was not declared in this scope
../pcap_binding.cc:251: error: ‘cur_addr’ was not declared in this scope
../pcap_binding.cc:277: error: ‘PCAP_IF_LOOPBACK’ was not declared in this scope
../pcap_binding.cc:284: error: ‘pcap_freealldevs’ was not declared in this scope
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> Close(const v8::Arguments&)’:
../pcap_binding.cc:293: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:293: error: ‘pcap_close’ was not declared in this scope
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> Fileno(const v8::Arguments&)’:
../pcap_binding.cc:303: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:303: error: ‘pcap_get_selectable_fd’ was not declared in this scope
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> Stats(const v8::Arguments&)’:
../pcap_binding.cc:313: error: aggregate ‘pcap_stat ps’ has incomplete type and cannot be defined
../pcap_binding.cc:315: error: ‘pcap_handle’ was not declared in this scope
../pcap_binding.cc:315: error: ‘pcap_stats’ was not declared in this scope
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> DefaultDevice(const v8::Arguments&)’:
../pcap_binding.cc:334: error: ‘PCAP_ERRBUF_SIZE’ was not declared in this scope
../pcap_binding.cc:339: error: ‘pcap_if_t’ was not declared in this scope
../pcap_binding.cc:339: error: ‘alldevs’ was not declared in this scope
../pcap_binding.cc:339: error: ‘dev’ was not declared in this scope
../pcap_binding.cc:340: error: ‘pcap_addr_t’ was not declared in this scope
../pcap_binding.cc:340: error: ‘addr’ was not declared in this scope
../pcap_binding.cc:343: error: ‘errbuf’ was not declared in this scope
../pcap_binding.cc:343: error: ‘pcap_findalldevs’ was not declared in this scope
../pcap_binding.cc:344: error: no matching function for call to ‘v8::String::New(<type error>)’
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1147: note: candidates are: static v8::Local<v8::String> v8::String::New(const char*, int)
/usr/local/Cellar/node/0.2.1/include/node/v8.h:1150: note:                 static v8::Local<v8::String> v8::String::New(const uint16_t*, int)
../pcap_binding.cc:348: error: ‘PCAP_IF_LOOPBACK’ was not declared in this scope
../pcap_binding.cc:363: error: ‘pcap_freealldevs’ was not declared in this scope
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> LibVersion(const v8::Arguments&)’:
../pcap_binding.cc:372: error: ‘pcap_lib_version’ was not declared in this scope
../pcap_binding.cc: At global scope:
../pcap_binding.cc:22: error: storage size of ‘fp’ isn’t known
Waf: Leaving directory `/usr/local/lib/node/.npm/pcap/0.2.1/package/build'
Build failed:  -> task failed (err #1): 
	{task: cxx pcap_binding.cc -> pcap_binding_1.o}
npm info pcap@0.2.1 Failed to exec install script
npm ERR! install failed Error: pcap@0.2.1 install: `node-waf configure build`
npm ERR! install failed `sh` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/local/Cellar/npm/0.2.0/libexec/lib/utils/exec.js:24:18)
npm ERR! install failed     at ChildProcess.emit (events:33:26)
npm ERR! install failed     at ChildProcess.onexit (child_process:151:12)
npm ERR! install failed     at node.js:769:9
npm info install failed rollback
npm info not installed pcap,0.2.1
npm info install failed rolled back
npm ERR! Error: pcap@0.2.1 install: `node-waf configure build`
npm ERR! `sh` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/Cellar/npm/0.2.0/libexec/lib/utils/exec.js:24:18)
npm ERR!     at ChildProcess.emit (events:33:26)
npm ERR!     at ChildProcess.onexit (child_process:151:12)
npm ERR!     at node.js:769:9
npm ERR! try running: 'npm help install'
npm ERR! Report this *entire* log at <http://github.com/isaacs/npm/issues>
npm ERR! or email it to <npm-@googlegroups.com>
npm not ok
</pre>

Looks like it expects to find pcap/pcap.h, but I only have /usr/include/pcap.h.

Any ideas?

**Comment by jmaxxz** [comment]
4 years later....closing as doubt anyone is still experiencing this issue with OSX 10.6 . Reopen if anyone has issues.

[Apple no longer supports 10.6](http://www.computerworld.com/article/2487996/malware-vulnerabilities/apple-retires-snow-leopard-from-support--leaves-1-in-5-macs-vulnerable-to-at.html)
