### ISSUE TITLE
Installation Issue using npm post v 10.35

### ISSUE THREAD

**Issue by vigneshshanmugam** [mranney/node_pcap#116]
OSX 10.9.4 
Node Version - 0.11.4

http://pastebin.com/1VemNhU9 

Works fine on Node stable (0.10.35)

**Comment by soulraven** [comment]
same problem here, on v0.12.0, is impossibile to install or do somthing.

**Comment by zerouid** [comment]
Can you try to install the github version instead:
```
npm install mranney/node_pcap
```

**Comment by soulraven** [comment]
try to install github versio, but still fail
http://pastebin.com/ZyJm45Nv

**Comment by jmaxxz** [comment]
Successfully building on both 0.11 and 0.12 in CI environment
node 0.11.16: https://travis-ci.org/jmaxxz/node_pcap/jobs/51467642
node 0.12.0 : https://travis-ci.org/jmaxxz/node_pcap/jobs/51467641

Try this:
```Bash
git clone git@github.com:mranney/node_pcap.git
cd node_pcap
npm install
```

**Comment by soulraven** [comment]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jmaxxz** [comment]
Ok try the http endpoint instead

```
git clone https://github.com/mranney/node_pcap.git
cd node_pcap
npm install
```

**Comment by soulraven** [comment]
now :))

module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/nodeCapture/node_modules/node_pcap/pcap.js:3:21)

**Comment by jmaxxz** [comment]
And you have libpcap w/headers installed?

```bash
sudo apt-get install libpcap-dev
```

**Comment by soulraven** [comment]
yes, is installed, still the same error

**Comment by jmaxxz** [comment]
Well, I am just about out of ideas. Will let you know if I think of anything else.

**Comment by soulraven** [comment]
the problem is that after npm install inside the node_pcap, no path is created build/Release/pcap_binding

**Comment by jmaxxz** [comment]
What if you mkdir that manually?

**Comment by tecfu** [comment]
This is the <b><i>only</i></b> install that worked for me on ubutu 14.04, node 0.12.2
```
git clone https://github.com/mranney/node_pcap.git
cd node_pcap
<b>sudo</b> npm install
```
Note:
```
npm install pcap
npm install mranney/node_pcap
```
failed.
